--- #YAML:1.0
name:               DBR
version:            1.4
abstract:           ~
author:  []
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:                 0
    Clone:                0
    Curses::UI:           0
    Data::Dumper:         0
    DateTime:             0
    DateTime::Locale:     0
    DateTime::TimeZone:   0
    DBD::mysql:           4.002
    DBD::SQLite:          1.20
    DBI:                  0
    Digest::MD5:          0
    File::Path:           1.08
    FileHandle:           0
    Getopt::Long:         0
    Moose:                0
    POSIX:                0
    Scalar::Util:         0
    Switch:               0
    Symbol:               0
    Test::More:           0.87
    Text::SimpleTable::AutoWidth:  0
    Time::HiRes:          0
    Time::ParseDate:      0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
